/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1.loginForm;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.io.PrintWriter;
import java.net.Socket;
import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import ortherLayout.panelHistoryPage;
import ortherLayout.panelProfilePage;
import ortherLayout.panelQrCodePage;
import ortherLayout.panelUpdatePage;

/**
 *
 * @author nhatnguyen
 */
public class HomePage extends javax.swing.JFrame {
    private Socket socket;
    private account user = new account();
    private panelHomePage homePage = new panelHomePage();

    /**
     * Creates new form HomePage
     */
    public HomePage(Socket socket) throws IOException {
//        setLocation(null);
        this.socket = socket;
        initComponents();     
//        panelHome.add(homePage);
        menuClicked(panelHomePage);
        receivedMeessageFromServer(this.user);
        setTextNameAndId(this.user);
    }

    public HomePage(){}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        sidepane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        idUser = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        firstName = new javax.swing.JLabel();
        logOutbtn = new javax.swing.JButton();
        paneHome = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        paneProfile = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        paneQrCode = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        paneHistory = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        paneUpdate = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        panelHomePage = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        panelProfilePage = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        fullName = new javax.swing.JLabel();
        cardId = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        birthDay = new javax.swing.JLabel();
        numberPhone = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        state = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        panelQrCodePage = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        panelUpdatePage = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        firstNameUpdate = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        lastNameUpdate = new javax.swing.JTextField();
        cardIdInformationUpdate = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        birthDayUpdate = new javax.swing.JTextField();
        numberPhoneUpdate = new javax.swing.JTextField();
        emailUpdate = new javax.swing.JTextField();
        addressUpdate = new javax.swing.JTextField();
        sendInformationUpdate = new javax.swing.JButton();
        nuBtnUpdate = new javax.swing.JRadioButton();
        namBtnUpdate = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepane.setBackground(new java.awt.Color(116, 214, 193));
        sidepane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("/home/nhatnguyen/Downloads/icons8-protect-128 (3).png")); // NOI18N
        sidepane.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 12, -1, -1));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("PC COVID");
        sidepane.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 12, -1, -1));

        jPanel3.setBackground(java.awt.Color.white);
        jPanel3.setForeground(java.awt.Color.white);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        sidepane.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-7, 70, 390, 10));

        jLabel4.setIcon(new javax.swing.ImageIcon("/home/nhatnguyen/Downloads/icons8-user-128.png")); // NOI18N
        jLabel4.setText("jLabel4");
        sidepane.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 127, 112));

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("ID:");
        sidepane.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        idUser.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        idUser.setForeground(java.awt.Color.white);
        sidepane.add(idUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 93, 29));

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("Name:");
        sidepane.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        firstName.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 24)); // NOI18N
        firstName.setForeground(java.awt.Color.white);
        sidepane.add(firstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 107, 29));

        logOutbtn.setBackground(java.awt.Color.white);
        logOutbtn.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        logOutbtn.setForeground(new java.awt.Color(116, 214, 193));
        logOutbtn.setText("Log out");
        logOutbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logOutbtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                logOutbtnMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOutbtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logOutbtnMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logOutbtnMouseEntered(evt);
            }
        });
        sidepane.add(logOutbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 750, 170, 52));

        paneHome.setBackground(new java.awt.Color(152, 234, 217));
        paneHome.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        paneHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                paneHomeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                paneHomeMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paneHomeMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                paneHomeMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                paneHomeMouseEntered(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon("/home/nhatnguyen/Downloads/icons8-home-50 (1).png")); // NOI18N
        jLabel7.setText("jLabel7");

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 27)); // NOI18N
        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("Home");

        javax.swing.GroupLayout paneHomeLayout = new javax.swing.GroupLayout(paneHome);
        paneHome.setLayout(paneHomeLayout);
        paneHomeLayout.setHorizontalGroup(
            paneHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneHomeLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jLabel8)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        paneHomeLayout.setVerticalGroup(
            paneHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        sidepane.add(paneHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 380, 60));

        paneProfile.setBackground(new java.awt.Color(152, 234, 217));
        paneProfile.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        paneProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                paneProfileMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                paneProfileMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paneProfileMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                paneProfileMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                paneProfileMouseEntered(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon("/home/nhatnguyen/Downloads/icons8-information-64 (1).png")); // NOI18N

        jLabel10.setFont(new java.awt.Font("Ubuntu", 1, 27)); // NOI18N
        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setText("Profile");

        javax.swing.GroupLayout paneProfileLayout = new javax.swing.GroupLayout(paneProfile);
        paneProfile.setLayout(paneProfileLayout);
        paneProfileLayout.setHorizontalGroup(
            paneProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneProfileLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel10)
                .addGap(0, 147, Short.MAX_VALUE))
        );
        paneProfileLayout.setVerticalGroup(
            paneProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(paneProfileLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        sidepane.add(paneProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 380, 60));

        paneQrCode.setBackground(new java.awt.Color(152, 234, 217));
        paneQrCode.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        paneQrCode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                paneQrCodeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                paneQrCodeMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paneQrCodeMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                paneQrCodeMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                paneQrCodeMouseEntered(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon("/home/nhatnguyen/Downloads/icons8-qr-code-64 (1).png")); // NOI18N

        jLabel12.setFont(new java.awt.Font("Ubuntu", 1, 27)); // NOI18N
        jLabel12.setForeground(java.awt.Color.white);
        jLabel12.setText("QR Code");

        javax.swing.GroupLayout paneQrCodeLayout = new javax.swing.GroupLayout(paneQrCode);
        paneQrCode.setLayout(paneQrCodeLayout);
        paneQrCodeLayout.setHorizontalGroup(
            paneQrCodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneQrCodeLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel12)
                .addContainerGap(128, Short.MAX_VALUE))
        );
        paneQrCodeLayout.setVerticalGroup(
            paneQrCodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneQrCodeLayout.createSequentialGroup()
                .addGroup(paneQrCodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneQrCodeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12))
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );

        sidepane.add(paneQrCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 380, 60));

        paneHistory.setBackground(new java.awt.Color(152, 234, 217));
        paneHistory.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        paneHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                paneHistoryMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                paneHistoryMouseReleased(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                paneHistoryMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                paneHistoryMouseEntered(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon("/home/nhatnguyen/Downloads/icons8-history-64 (1).png")); // NOI18N

        jLabel14.setFont(new java.awt.Font("Ubuntu", 1, 27)); // NOI18N
        jLabel14.setForeground(java.awt.Color.white);
        jLabel14.setText("History");

        javax.swing.GroupLayout paneHistoryLayout = new javax.swing.GroupLayout(paneHistory);
        paneHistory.setLayout(paneHistoryLayout);
        paneHistoryLayout.setHorizontalGroup(
            paneHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneHistoryLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel13)
                .addGap(36, 36, 36)
                .addComponent(jLabel14)
                .addContainerGap(143, Short.MAX_VALUE))
        );
        paneHistoryLayout.setVerticalGroup(
            paneHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(paneHistoryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        sidepane.add(paneHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 380, 60));

        paneUpdate.setBackground(new java.awt.Color(152, 234, 217));
        paneUpdate.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        paneUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                paneUpdateMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                paneUpdateMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paneUpdateMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                paneUpdateMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                paneUpdateMouseEntered(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon("/home/nhatnguyen/Downloads/icons8-update-left-rotation-50 (1).png")); // NOI18N
        jLabel15.setText("jLabel15");

        jLabel16.setFont(new java.awt.Font("Ubuntu", 1, 27)); // NOI18N
        jLabel16.setForeground(java.awt.Color.white);
        jLabel16.setText("Update");

        javax.swing.GroupLayout paneUpdateLayout = new javax.swing.GroupLayout(paneUpdate);
        paneUpdate.setLayout(paneUpdateLayout);
        paneUpdateLayout.setHorizontalGroup(
            paneUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneUpdateLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel16)
                .addContainerGap(142, Short.MAX_VALUE))
        );
        paneUpdateLayout.setVerticalGroup(
            paneUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneUpdateLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(paneUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)))
        );

        sidepane.add(paneUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 380, 60));

        jLabel20.setBackground(java.awt.Color.white);
        jLabel20.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        jLabel20.setForeground(java.awt.Color.white);
        jLabel20.setText("KHAI BÁO Y TẾ - GIẢM THIỂU LÂY LAN");
        sidepane.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 47, -1, 17));

        jPanel1.add(sidepane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 840));

        jPanel4.setBackground(java.awt.Color.white);

        jPanel2.setBackground(java.awt.Color.white);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelHomePage.setBackground(new java.awt.Color(116, 214, 193));

        jPanel5.setBackground(java.awt.Color.white);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        jLabel18.setIcon(new javax.swing.ImageIcon("/home/nhatnguyen/Downloads/pngwing.com (1).png")); // NOI18N

        jLabel17.setIcon(new javax.swing.ImageIcon("/home/nhatnguyen/Downloads/icons8-protect-100.png")); // NOI18N

        jLabel19.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel19.setForeground(java.awt.Color.white);
        jLabel19.setText("PC COVID");

        jLabel3.setBackground(java.awt.Color.white);
        jLabel3.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 18)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("KHAI BÁO Y TẾ - GIẢM THIỂU LÂY LAN");

        jLabel21.setIcon(new javax.swing.ImageIcon("/home/nhatnguyen/Downloads/—Pngtree—cegah dan tangkal covid-19 dengan_6011555 (2).png")); // NOI18N

        jLabel22.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 36)); // NOI18N
        jLabel22.setForeground(java.awt.Color.white);
        jLabel22.setText("Thực hiện quy định 5K");

        jLabel37.setIcon(new javax.swing.ImageIcon("/home/nhatnguyen/Downloads/icons8-attention-96.png")); // NOI18N

        javax.swing.GroupLayout panelHomePageLayout = new javax.swing.GroupLayout(panelHomePage);
        panelHomePage.setLayout(panelHomePageLayout);
        panelHomePageLayout.setHorizontalGroup(
            panelHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHomePageLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(124, 124, 124))
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelHomePageLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel37)
                .addGroup(panelHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHomePageLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel22))
                    .addGroup(panelHomePageLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel21)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelHomePageLayout.setVerticalGroup(
            panelHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomePageLayout.createSequentialGroup()
                .addGroup(panelHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHomePageLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(panelHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addGroup(panelHomePageLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelHomePageLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel18)))
                .addGap(21, 21, 21)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(panelHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHomePageLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel21))
                    .addComponent(jLabel37))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jPanel2.add(panelHomePage, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, 1013, -1));

        panelProfilePage.setBackground(new java.awt.Color(116, 214, 193));
        panelProfilePage.setPreferredSize(new java.awt.Dimension(991, 888));

        jPanel8.setBackground(java.awt.Color.white);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        jLabel38.setIcon(new javax.swing.ImageIcon("/home/nhatnguyen/Downloads/pngwing.com (1).png")); // NOI18N

        jLabel39.setIcon(new javax.swing.ImageIcon("/home/nhatnguyen/Downloads/icons8-protect-100.png")); // NOI18N

        jLabel40.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel40.setForeground(java.awt.Color.white);
        jLabel40.setText("PC COVID");

        jLabel41.setBackground(java.awt.Color.white);
        jLabel41.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 18)); // NOI18N
        jLabel41.setForeground(java.awt.Color.white);
        jLabel41.setText("KHAI BÁO Y TẾ - GIẢM THIỂU LÂY LAN");

        jLabel42.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 48)); // NOI18N
        jLabel42.setForeground(java.awt.Color.white);
        jLabel42.setText("Thông tin cơ bản");

        jLabel43.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 24)); // NOI18N
        jLabel43.setForeground(java.awt.Color.white);
        jLabel43.setText("Trạng thái dịch tễ:");

        jLabel44.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 24)); // NOI18N
        jLabel44.setForeground(java.awt.Color.white);
        jLabel44.setText("Họ và tên:");

        jLabel45.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 24)); // NOI18N
        jLabel45.setForeground(java.awt.Color.white);
        jLabel45.setText("Số CCCD:");

        jLabel46.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 24)); // NOI18N
        jLabel46.setForeground(java.awt.Color.white);
        jLabel46.setText("Ngày sinh:");

        jLabel47.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 24)); // NOI18N
        jLabel47.setForeground(java.awt.Color.white);
        jLabel47.setText("Giới tính:");

        jLabel48.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 24)); // NOI18N
        jLabel48.setForeground(java.awt.Color.white);
        jLabel48.setText("Số điện thoại:");

        jLabel49.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 24)); // NOI18N
        jLabel49.setForeground(java.awt.Color.white);
        jLabel49.setText("Email:");

        jLabel50.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 24)); // NOI18N
        jLabel50.setForeground(java.awt.Color.white);
        jLabel50.setText("Địa chỉ:");

        fullName.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 22)); // NOI18N
        fullName.setForeground(java.awt.Color.white);

        cardId.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 22)); // NOI18N
        cardId.setForeground(java.awt.Color.white);

        gender.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 22)); // NOI18N
        gender.setForeground(java.awt.Color.white);

        birthDay.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 22)); // NOI18N
        birthDay.setForeground(java.awt.Color.white);

        numberPhone.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 22)); // NOI18N
        numberPhone.setForeground(java.awt.Color.white);

        email.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 22)); // NOI18N
        email.setForeground(java.awt.Color.white);

        address.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 22)); // NOI18N
        address.setForeground(java.awt.Color.white);

        state.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 22)); // NOI18N
        state.setForeground(java.awt.Color.white);

        jPanel9.setBackground(java.awt.Color.white);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jLabel51.setIcon(new javax.swing.ImageIcon("/home/nhatnguyen/Downloads/icons8-list-100.png")); // NOI18N

        javax.swing.GroupLayout panelProfilePageLayout = new javax.swing.GroupLayout(panelProfilePage);
        panelProfilePage.setLayout(panelProfilePageLayout);
        panelProfilePageLayout.setHorizontalGroup(
            panelProfilePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProfilePageLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel39)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelProfilePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel40)
                    .addComponent(jLabel41))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel38)
                .addGap(120, 120, 120))
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProfilePageLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel47)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel43)
                .addGap(18, 18, 18)
                .addComponent(state, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProfilePageLayout.createSequentialGroup()
                .addGroup(panelProfilePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelProfilePageLayout.createSequentialGroup()
                        .addContainerGap(491, Short.MAX_VALUE)
                        .addComponent(jLabel48)
                        .addGap(18, 18, 18)
                        .addComponent(numberPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelProfilePageLayout.createSequentialGroup()
                        .addGroup(panelProfilePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProfilePageLayout.createSequentialGroup()
                                .addComponent(jLabel45)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cardId, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(panelProfilePageLayout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addGroup(panelProfilePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelProfilePageLayout.createSequentialGroup()
                                        .addComponent(jLabel44)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fullName, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelProfilePageLayout.createSequentialGroup()
                                        .addComponent(jLabel46)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(birthDay, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(32, 32, 32)))
                        .addGroup(panelProfilePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelProfilePageLayout.createSequentialGroup()
                                .addComponent(jLabel50)
                                .addGap(18, 18, 18)
                                .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE))
                            .addGroup(panelProfilePageLayout.createSequentialGroup()
                                .addComponent(jLabel49)
                                .addGap(18, 18, 18)
                                .addComponent(email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(24, 24, 24))
            .addGroup(panelProfilePageLayout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jLabel51)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelProfilePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelProfilePageLayout.setVerticalGroup(
            panelProfilePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProfilePageLayout.createSequentialGroup()
                .addGroup(panelProfilePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProfilePageLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(panelProfilePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel39)
                            .addGroup(panelProfilePageLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel40)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelProfilePageLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel38)))
                .addGap(21, 21, 21)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelProfilePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProfilePageLayout.createSequentialGroup()
                        .addComponent(jLabel42)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel51))
                .addGap(45, 45, 45)
                .addGroup(panelProfilePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelProfilePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fullName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel48)
                        .addComponent(numberPhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(panelProfilePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(jLabel49)
                    .addComponent(cardId, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(52, 52, 52)
                .addGroup(panelProfilePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(jLabel50)
                    .addComponent(birthDay, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(address, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(59, 59, 59)
                .addGroup(panelProfilePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel47)
                    .addComponent(jLabel43)
                    .addComponent(gender, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(state, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(143, 143, 143))
        );

        jPanel2.add(panelProfilePage, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, 1013, -1));

        panelQrCodePage.setBackground(new java.awt.Color(116, 214, 193));

        jPanel10.setBackground(java.awt.Color.white);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        jLabel28.setIcon(new javax.swing.ImageIcon("/home/nhatnguyen/Downloads/pngwing.com (1).png")); // NOI18N

        jLabel54.setIcon(new javax.swing.ImageIcon("/home/nhatnguyen/Downloads/icons8-protect-100.png")); // NOI18N

        jLabel55.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel55.setForeground(java.awt.Color.white);
        jLabel55.setText("PC COVID");

        jLabel56.setBackground(java.awt.Color.white);
        jLabel56.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 18)); // NOI18N
        jLabel56.setForeground(java.awt.Color.white);
        jLabel56.setText("KHAI BÁO Y TẾ - GIẢM THIỂU LÂY LAN");

        jLabel57.setIcon(new javax.swing.ImageIcon("/home/nhatnguyen/Downloads/—Pngtree—cegah dan tangkal covid-19 dengan_6011555 (2).png")); // NOI18N

        jLabel58.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 36)); // NOI18N
        jLabel58.setForeground(java.awt.Color.white);
        jLabel58.setText("Thực hiện quy định 5K");

        jLabel59.setIcon(new javax.swing.ImageIcon("/home/nhatnguyen/Downloads/icons8-attention-96.png")); // NOI18N

        javax.swing.GroupLayout panelQrCodePageLayout = new javax.swing.GroupLayout(panelQrCodePage);
        panelQrCodePage.setLayout(panelQrCodePageLayout);
        panelQrCodePageLayout.setHorizontalGroup(
            panelQrCodePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelQrCodePageLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel54)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelQrCodePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel55)
                    .addComponent(jLabel56))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(jLabel28)
                .addGap(124, 124, 124))
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelQrCodePageLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel59)
                .addGroup(panelQrCodePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelQrCodePageLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel58))
                    .addGroup(panelQrCodePageLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel57)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelQrCodePageLayout.setVerticalGroup(
            panelQrCodePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQrCodePageLayout.createSequentialGroup()
                .addGroup(panelQrCodePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelQrCodePageLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(panelQrCodePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel54)
                            .addGroup(panelQrCodePageLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel55)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelQrCodePageLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel28)))
                .addGap(21, 21, 21)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(panelQrCodePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelQrCodePageLayout.createSequentialGroup()
                        .addComponent(jLabel58)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel57))
                    .addComponent(jLabel59))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jPanel2.add(panelQrCodePage, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, 1013, -1));

        panelUpdatePage.setBackground(new java.awt.Color(116, 214, 193));
        panelUpdatePage.setPreferredSize(new java.awt.Dimension(991, 888));
        panelUpdatePage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(java.awt.Color.white);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        panelUpdatePage.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 1010, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon("/home/nhatnguyen/Downloads/pngwing.com (1).png")); // NOI18N
        panelUpdatePage.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(596, 12, -1, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon("/home/nhatnguyen/Downloads/icons8-protect-100.png")); // NOI18N
        panelUpdatePage.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 47, -1, -1));

        jLabel25.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel25.setForeground(java.awt.Color.white);
        jLabel25.setText("PC COVID");
        panelUpdatePage.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 56, -1, -1));

        jLabel26.setBackground(java.awt.Color.white);
        jLabel26.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 18)); // NOI18N
        jLabel26.setForeground(java.awt.Color.white);
        jLabel26.setText("KHAI BÁO Y TẾ - GIẢM THIỂU LÂY LAN");
        panelUpdatePage.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, 17));

        jLabel27.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 48)); // NOI18N
        jLabel27.setForeground(java.awt.Color.white);
        jLabel27.setText("Update thông tin ");
        panelUpdatePage.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 246, -1, -1));

        jLabel29.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 24)); // NOI18N
        jLabel29.setForeground(java.awt.Color.white);
        jLabel29.setText("Tên đầu:");
        panelUpdatePage.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, -1));

        jLabel30.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 24)); // NOI18N
        jLabel30.setForeground(java.awt.Color.white);
        jLabel30.setText("Số CCCD:");
        panelUpdatePage.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 560, -1, -1));

        jLabel31.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 24)); // NOI18N
        jLabel31.setForeground(java.awt.Color.white);
        jLabel31.setText("Ngày sinh:");
        panelUpdatePage.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 650, -1, -1));

        jLabel32.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 24)); // NOI18N
        jLabel32.setForeground(java.awt.Color.white);
        jLabel32.setText("Giới tính:");
        panelUpdatePage.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 650, -1, -1));

        jLabel33.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 24)); // NOI18N
        jLabel33.setForeground(java.awt.Color.white);
        jLabel33.setText("Số điện thoại:");
        panelUpdatePage.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 390, -1, -1));

        jLabel34.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 24)); // NOI18N
        jLabel34.setForeground(java.awt.Color.white);
        jLabel34.setText("Email:");
        panelUpdatePage.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 480, -1, -1));

        jLabel35.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 24)); // NOI18N
        jLabel35.setForeground(java.awt.Color.white);
        jLabel35.setText("Địa chỉ:");
        panelUpdatePage.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 560, -1, -1));

        jPanel7.setBackground(java.awt.Color.white);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        panelUpdatePage.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 322, 425, -1));

        jLabel36.setIcon(new javax.swing.ImageIcon("/home/nhatnguyen/Downloads/icons8-list-100.png")); // NOI18N
        panelUpdatePage.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 246, -1, -1));

        firstNameUpdate.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 24)); // NOI18N
        firstNameUpdate.setForeground(new java.awt.Color(116, 214, 193));
        panelUpdatePage.add(firstNameUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 251, 35));

        jLabel52.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 24)); // NOI18N
        jLabel52.setForeground(java.awt.Color.white);
        jLabel52.setText("Tên cuối:");
        panelUpdatePage.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, -1, -1));

        lastNameUpdate.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 24)); // NOI18N
        lastNameUpdate.setForeground(new java.awt.Color(116, 214, 193));
        panelUpdatePage.add(lastNameUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, 251, 35));

        cardIdInformationUpdate.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 24)); // NOI18N
        cardIdInformationUpdate.setForeground(new java.awt.Color(116, 214, 193));
        panelUpdatePage.add(cardIdInformationUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 560, 251, 35));

        jLabel53.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel53.setForeground(java.awt.Color.white);
        jLabel53.setText("(dd-mm-yyyy)");
        panelUpdatePage.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 690, -1, -1));

        birthDayUpdate.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 24)); // NOI18N
        birthDayUpdate.setForeground(new java.awt.Color(116, 214, 193));
        panelUpdatePage.add(birthDayUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 650, 251, 35));

        numberPhoneUpdate.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 24)); // NOI18N
        numberPhoneUpdate.setForeground(new java.awt.Color(116, 214, 193));
        panelUpdatePage.add(numberPhoneUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 390, 251, 35));

        emailUpdate.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 24)); // NOI18N
        emailUpdate.setForeground(new java.awt.Color(116, 214, 193));
        panelUpdatePage.add(emailUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 470, 251, 35));

        addressUpdate.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 24)); // NOI18N
        addressUpdate.setForeground(new java.awt.Color(116, 214, 193));
        panelUpdatePage.add(addressUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 560, 251, 35));

        sendInformationUpdate.setFont(new java.awt.Font("Ubuntu", 1, 30)); // NOI18N
        sendInformationUpdate.setForeground(new java.awt.Color(116, 214, 193));
        sendInformationUpdate.setText("Send your information");
        sendInformationUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendInformationUpdateMouseClicked(evt);
            }
        });
        panelUpdatePage.add(sendInformationUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 730, 430, 80));

        nuBtnUpdate.setBackground(java.awt.Color.white);
        buttonGroup1.add(nuBtnUpdate);
        nuBtnUpdate.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 24)); // NOI18N
        nuBtnUpdate.setForeground(java.awt.Color.white);
        nuBtnUpdate.setText("Nữ");
        panelUpdatePage.add(nuBtnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 650, -1, -1));

        namBtnUpdate.setBackground(java.awt.Color.white);
        buttonGroup1.add(namBtnUpdate);
        namBtnUpdate.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 24)); // NOI18N
        namBtnUpdate.setForeground(java.awt.Color.white);
        namBtnUpdate.setText("Nam");
        panelUpdatePage.add(namBtnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 650, -1, -1));

        jPanel2.add(panelUpdatePage, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, 1013, -1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1025, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 888, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 1010, 840));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logOutbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutbtnMouseClicked
        // TODO add your handling code here:
        dispose();
        try {
            sendMessageToServer("5",socket);
        } catch (Exception e) {
            System.out.println("can't send choice(5) to Server");
        }
        
        NewSignUp login = null;
        try {
            login = new NewSignUp("");
        } catch (IOException ex) {
            Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            login.startLayout();
        } catch (Exception e) {
            System.out.println("can't start NewSignUp layout");
        }
        
    }//GEN-LAST:event_logOutbtnMouseClicked

    private void paneHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneHomeMouseEntered
        paneHome.setBackground(new Color(220,153,141));// TODO add your handling code here:
    }//GEN-LAST:event_paneHomeMouseEntered

    private void paneHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneHomeMouseExited
        // TODO add your handling code here:
        paneHome.setBackground(new Color(152,234,217));
    }//GEN-LAST:event_paneHomeMouseExited

    private void paneHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneHomeMousePressed
        // TODO add your handling code here:
        paneHome.setBackground(new Color(220,153,141));
    }//GEN-LAST:event_paneHomeMousePressed

    private void paneHomeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneHomeMouseReleased
        // TODO add your handling code here:
        paneHome.setBackground(new Color(220,153,141));
    }//GEN-LAST:event_paneHomeMouseReleased

    private void paneProfileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneProfileMouseEntered
        // TODO add your handling code here:
        paneProfile.setBackground(new Color(220,153,141));
    }//GEN-LAST:event_paneProfileMouseEntered

    private void paneProfileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneProfileMouseExited
        // TODO add your handling code here:
        paneProfile.setBackground(new Color(152,234,217));
    }//GEN-LAST:event_paneProfileMouseExited

    private void paneProfileMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneProfileMousePressed
        // TODO add your handling code here:
        paneProfile.setBackground(new Color(220,153,141));
    }//GEN-LAST:event_paneProfileMousePressed

    private void paneProfileMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneProfileMouseReleased
        // TODO add your handling code here:
        paneProfile.setBackground(new Color(220,153,141));
    }//GEN-LAST:event_paneProfileMouseReleased

    private void paneQrCodeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneQrCodeMouseEntered
        // TODO add your handling code here:
        paneQrCode.setBackground(new Color(220,153,141));
    }//GEN-LAST:event_paneQrCodeMouseEntered

    private void paneQrCodeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneQrCodeMouseExited
        // TODO add your handling code here:
        paneQrCode.setBackground(new Color(152,234,217));
    }//GEN-LAST:event_paneQrCodeMouseExited

    private void paneQrCodeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneQrCodeMousePressed
        // TODO add your handling code here:
        paneQrCode.setBackground(new Color(220,153,141));
    }//GEN-LAST:event_paneQrCodeMousePressed

    private void paneQrCodeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneQrCodeMouseReleased
        // TODO add your handling code here:
        paneQrCode.setBackground(new Color(220,153,141));
    }//GEN-LAST:event_paneQrCodeMouseReleased

    private void paneHistoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneHistoryMouseEntered
        // TODO add your handling code here:
        paneHistory.setBackground(new Color(220,153,141));
    }//GEN-LAST:event_paneHistoryMouseEntered

    private void paneHistoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneHistoryMouseExited
        // TODO add your handling code here:
        paneHistory.setBackground(new Color(152,234,217));
    }//GEN-LAST:event_paneHistoryMouseExited

    private void paneHistoryMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneHistoryMousePressed
        // TODO add your handling code here:
        paneHistory.setBackground(new Color(220,153,141));
    }//GEN-LAST:event_paneHistoryMousePressed

    private void paneHistoryMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneHistoryMouseReleased
        // TODO add your handling code here:
        paneHistory.setBackground(new Color(220,153,141));
    }//GEN-LAST:event_paneHistoryMouseReleased

    private void paneUpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneUpdateMouseEntered
        // TODO add your handling code here:
        paneUpdate.setBackground(new Color(220,153,141));
    }//GEN-LAST:event_paneUpdateMouseEntered

    private void paneUpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneUpdateMouseExited
        // TODO add your handling code here:
        paneUpdate.setBackground(new Color(152,234,217));
    }//GEN-LAST:event_paneUpdateMouseExited

    private void paneUpdateMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneUpdateMousePressed
        // TODO add your handling code here:
        paneUpdate.setBackground(new Color(220,153,141));
    }//GEN-LAST:event_paneUpdateMousePressed

    private void paneUpdateMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneUpdateMouseReleased
        // TODO add your handling code here:
        paneUpdate.setBackground(new Color(220,153,141));
    }//GEN-LAST:event_paneUpdateMouseReleased

    private void paneHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneHomeMouseClicked
        // TODO add your handling code here:
        try {
            menuClicked(panelHomePage);
        } catch (Exception e) {
            System.out.println("can't start layout");
        }
        
    }//GEN-LAST:event_paneHomeMouseClicked

    private void paneProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneProfileMouseClicked
        // TODO add your handling code here:
        try {
            menuClicked(panelProfilePage);
            sendMessageToServer("1",socket);
            InputStream istream = null;
            try {
                istream = socket.getInputStream();
            } catch (IOException ex) {
                Logger.getLogger(NewSignUp.class.getName()).log(Level.SEVERE, null, ex);
            }
            BufferedReader receiveRead = new BufferedReader(new InputStreamReader(istream), 1024);
            try {
                checkOutPut(receiveRead,socket,this.user);
            } catch (Exception e) {
                System.out.println("can't check out put");
            }
            setInformationUser();
            setTextNameAndId(user); 
        } catch (Exception e) {
            System.out.println("can't start layout");
        }
    }//GEN-LAST:event_paneProfileMouseClicked

    private void paneUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneUpdateMouseClicked
        // TODO add your handling code here:
        try {
            menuClicked(panelUpdatePage);
            setInformationUpdateAccount();
        } catch (Exception e) {
            System.out.println("can't start layout");
        }
    }//GEN-LAST:event_paneUpdateMouseClicked

    private void paneQrCodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneQrCodeMouseClicked
        // TODO add your handling code here:
        try {
            menuClicked(panelQrCodePage);
        } catch (Exception e) {
            System.out.println("can't start layout");
        }
    }//GEN-LAST:event_paneQrCodeMouseClicked

    private void logOutbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutbtnMouseEntered
        // TODO add your handling code here:
        logOutbtn.setBackground(new Color(220,153,141));
    }//GEN-LAST:event_logOutbtnMouseEntered

    private void logOutbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutbtnMouseExited
        // TODO add your handling code here:
        logOutbtn.setBackground(Color.WHITE);
    }//GEN-LAST:event_logOutbtnMouseExited

    private void logOutbtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutbtnMousePressed
        // TODO add your handling code here:
        logOutbtn.setBackground(new Color(220,153,141));
    }//GEN-LAST:event_logOutbtnMousePressed

    private void logOutbtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutbtnMouseReleased
        // TODO add your handling code here:
        logOutbtn.setBackground(new Color(220,153,141));
    }//GEN-LAST:event_logOutbtnMouseReleased

    private void sendInformationUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendInformationUpdateMouseClicked
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(jLabel3,
                        "Bạn muốn update thông tin cá nhân như trên?",
                        "Xác nhận",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE);
        if(result == JOptionPane.YES_OPTION){
            try {
                sendMessageToServer("4", socket);
                String messageUpdate = createInforUpdateAccount();
                sendMessageToServer(messageUpdate, socket);
            } catch (Exception e) {
            }            
        }
        try {
                String receivedMessage;
                InputStream istream = socket.getInputStream();
                BufferedReader receiveRead = new BufferedReader(new InputStreamReader(istream), 1024);
                receivedMessage = getMessageFromServer(receiveRead,socket);
                if(!receivedMessage.equals("")){
                    JOptionPane.showMessageDialog(jLabel3,
                    receivedMessage,
                    "From Server",
                    JOptionPane.INFORMATION_MESSAGE);
                }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_sendInformationUpdateMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new HomePage().setVisible(true);
//            }
//        });
//    } 

    private void setInformationUpdateAccount(){
        firstNameUpdate.setText(user.getFirstName());
        lastNameUpdate.setText(user.getLastname());
        cardIdInformationUpdate.setText(user.getCardId());
        birthDayUpdate.setText(user.getBirthOfDay());
        if(user.getGender().equals("Nam")){
            namBtnUpdate.setSelected(true);
        }else{
            nuBtnUpdate.setSelected(true);
        }
        numberPhoneUpdate.setText(user.getNumberPhone());
        emailUpdate.setText(user.getEmail());
        addressUpdate.setText(user.getAddress());
    }

    private String createInforUpdateAccount(){
        String iduser = user.getIdUser();
        String firstName = firstNameUpdate.getText();
        String lastName = lastNameUpdate.getText();
        String cardId = cardIdInformationUpdate.getText();
        String birthDay = birthDayUpdate.getText();
        String gender;
        if(namBtnUpdate.isSelected()){
            gender = "Nam";
        }else{
            gender = "Nu";
        }
        String numberPhone = numberPhoneUpdate.getText();
        String email = emailUpdate.getText();
        String address = addressUpdate.getText();
        String message = createInforAccountMessage(iduser,firstName,lastName,cardId,birthDay,gender,numberPhone,email,address,"normal");
        return message;
    }

    private String createInforAccountMessage(String idUser, String firstName, String lastName, String cardId, String birthday, String gender, String numberPhone,String email, String address, String state){
        return idUser + "_" + firstName + "_" + lastName + "_" + cardId + "_" + birthday + "_" + gender + "_" + numberPhone + "_" +email + "_" + address + "_" + state;
    }

    private void setInformationUser(){
        fullName.setText(user.getLastname() +" "+ user.getFirstName());
        gender.setText(user.getGender());
        cardId.setText(user.getCardId());
        birthDay.setText(user.getBirthOfDay());
        numberPhone.setText(user.getNumberPhone());
        email.setText(user.getEmail());
        address.setText(user.getAddress());
        state.setText(user.getState());
        state.setBackground(Color.RED);
    }
    

    private void sendMessageToServer(String str, Socket sock) throws IOException {
        OutputStream ostream = sock.getOutputStream();
        PrintWriter pwrite = new PrintWriter(ostream, true);
        pwrite.println(str);       // sending to server
        pwrite.flush();            // flush the data
    }
    
    private static String removeNonAscii(String s){
        StringBuffer sb = new StringBuffer();
        for(int i=0; i<s.length(); ++i){
            if(s.charAt(i) < 128){
                sb.append(s.charAt(i));
            }
        }
        return sb.toString();
    }

    private static String replaceUnreadable(String s){
        return s.replaceAll("\\P{Print}", "");
    }
   
    public void startLayout(Socket socket){
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new HomePage(socket).setVisible(true);
                } catch (Exception e) {
                }              
            }
        });
    }

    public void menuClicked(JPanel jpanel) throws IOException{
          panelHomePage.setVisible(false);
          panelProfilePage.setVisible(false);
        panelUpdatePage.setVisible(false);
        panelQrCodePage.setVisible(false);
//        updatepage.setVisible(false);

        jpanel.setVisible(true);
    }

    

    public void receivedMeessageFromServer(account user){
        InputStream istream = null;
        try {
            istream = socket.getInputStream();
        } catch (IOException ex) {
            Logger.getLogger(NewSignUp.class.getName()).log(Level.SEVERE, null, ex);
        }
        BufferedReader receiveRead = new BufferedReader(new InputStreamReader(istream), 1024);
        try {
                checkOutPut(receiveRead,socket,user);
        } catch (Exception e) {
                System.out.println("can't check out put");
        }
    }

    private void checkOutPut(BufferedReader receiveRead, Socket socket, account user) throws IOException {
        String receiveMessage;
        receiveMessage = String.valueOf(receiveRead.readLine());
        receiveMessage = removeNonAscii(receiveMessage);
        receiveMessage = replaceUnreadable(receiveMessage);
        if(!Objects.equals(receiveMessage, "0")) //receive from server
        {
            System.out.print("from server: ");
            System.out.println(receiveMessage); // displaying at DOS prompt
            inputTheUser(receiveMessage, user);
        }
    }

    private String getMessageFromServer(BufferedReader receiveRead, Socket socket) throws IOException {
        String receiveMessage;
        receiveMessage = String.valueOf(receiveRead.readLine());
        receiveMessage = removeNonAscii(receiveMessage);
        receiveMessage = replaceUnreadable(receiveMessage);
        if(!Objects.equals(receiveMessage, "0")) //receive from server
        {
            System.out.print("from server: ");
            System.out.println(receiveMessage); // displaying at DOS prompt
        }
        return receiveMessage;
    }

    private void inputTheUser(String receiveMessage, account user) {
        String[] listInfor = receiveMessage.split("_");
        user.setIdUser(listInfor[0]);
        user.setFirstName(listInfor[1]);
        user.setLastname(listInfor[2]);
        user.setCardId(listInfor[3]);
        user.setBirthOfDay(listInfor[4]);
        user.setGender(listInfor[5]);
        user.setNumberPhone(listInfor[6]);
        user.setEmail(listInfor[7]);
        user.setAddress(listInfor[8]);
        user.setState(listInfor[9]);
    }

    private void setTextNameAndId(account user){
        firstName.setText(user.getFirstName());
        idUser.setText(user.getIdUser());
    }
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address;
    private javax.swing.JTextField addressUpdate;
    private javax.swing.JLabel birthDay;
    private javax.swing.JTextField birthDayUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel cardId;
    private javax.swing.JTextField cardIdInformationUpdate;
    private javax.swing.JLabel email;
    private javax.swing.JTextField emailUpdate;
    private javax.swing.JLabel firstName;
    private javax.swing.JTextField firstNameUpdate;
    private javax.swing.JLabel fullName;
    private javax.swing.JLabel gender;
    private javax.swing.JLabel idUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField lastNameUpdate;
    private javax.swing.JButton logOutbtn;
    private javax.swing.JRadioButton namBtnUpdate;
    private javax.swing.JRadioButton nuBtnUpdate;
    private javax.swing.JLabel numberPhone;
    private javax.swing.JTextField numberPhoneUpdate;
    private javax.swing.JPanel paneHistory;
    private javax.swing.JPanel paneHome;
    private javax.swing.JPanel paneProfile;
    private javax.swing.JPanel paneQrCode;
    private javax.swing.JPanel paneUpdate;
    private javax.swing.JPanel panelHomePage;
    private javax.swing.JPanel panelProfilePage;
    private javax.swing.JPanel panelQrCodePage;
    private javax.swing.JPanel panelUpdatePage;
    private javax.swing.JButton sendInformationUpdate;
    private javax.swing.JPanel sidepane;
    private javax.swing.JLabel state;
    // End of variables declaration//GEN-END:variables
}
