/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1.loginForm;

import API.City;
import DataCity.CityHandler;
import com.mycompany.mavenproject1.loginForm.VNCharacter.VNCharacterUtils;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.io.PrintWriter;
import java.net.Socket;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Objects;
import javax.swing.JOptionPane;

/**
 *
 * @author nhatnguyen
 */
public class LocalPage extends javax.swing.JFrame {
    private Socket socket;
    private account user = new account();
    private static ArrayList<City> listCity = CityHandler.getListCityHandler();

    /**
     * Creates new form LocalPage
     */
    public LocalPage(Socket socket, account user) {
        this.socket = socket;
        this.user = user;
        initComponents();
        Dimension objDimension = Toolkit.getDefaultToolkit().getScreenSize();
        int iCoordX = (objDimension.width - this.getWidth()) / 8;
        int iCoordY = (objDimension.height - this.getHeight()) / 2;
        this.setLocation(iCoordX, iCoordY);
        addCity();
        addInforUser();
    }

    public LocalPage() {
    }

 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        vehicle3 = new javax.swing.JRadioButton();
        vehicle = new javax.swing.JRadioButton();
        vehicle2 = new javax.swing.JRadioButton();
        numberOfVehicle = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        datePicker = new com.github.lgooddatepicker.components.DatePicker();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        citysCome = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        districtsCome = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        addressCome = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        citysTo = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        districtsTo = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        addressTo = new javax.swing.JTextField();
        cancel = new javax.swing.JButton();
        submit = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        firstName = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        idUser = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        state = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cardId = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.white);

        jPanel2.setBackground(new java.awt.Color(116, 214, 193));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setIcon(new javax.swing.ImageIcon("/home/nhatnguyen/anh/icons8-protect-128 (3).png")); // NOI18N
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 12, -1, -1));

        jLabel20.setBackground(java.awt.Color.white);
        jLabel20.setFont(new java.awt.Font("DialogInput", 1, 15)); // NOI18N
        jLabel20.setForeground(java.awt.Color.white);
        jLabel20.setText("KHAI BÁO Y TẾ - GIẢM THIỂU LÂY LAN");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 47, -1, 17));

        jLabel11.setFont(new java.awt.Font("Ubuntu", 1, 27)); // NOI18N
        jLabel11.setForeground(java.awt.Color.white);
        jLabel11.setText("PC COVID");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 12, -1, -1));

        jPanel3.setBackground(new java.awt.Color(220, 153, 141));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setIcon(new javax.swing.ImageIcon("/home/nhatnguyen/anh/walk (2).png")); // NOI18N
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 88));

        jLabel14.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 48)); // NOI18N
        jLabel14.setForeground(java.awt.Color.white);
        jLabel14.setText("Khai báo di chuyển nội địa");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        jLabel15.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 36)); // NOI18N
        jLabel15.setForeground(java.awt.Color.white);
        jLabel15.setText("2. Nơi người khai đi");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, -1, -1));

        buttonGroup1.add(vehicle3);
        vehicle3.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 24)); // NOI18N
        vehicle3.setForeground(java.awt.Color.white);
        vehicle3.setText("Tàu thuyền");
        vehicle3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicle3ActionPerformed(evt);
            }
        });
        jPanel3.add(vehicle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));

        buttonGroup1.add(vehicle);
        vehicle.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 24)); // NOI18N
        vehicle.setForeground(java.awt.Color.white);
        vehicle.setSelected(true);
        vehicle.setText("Phương tiện cá nhân");
        vehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleActionPerformed(evt);
            }
        });
        jPanel3.add(vehicle, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        buttonGroup1.add(vehicle2);
        vehicle2.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 24)); // NOI18N
        vehicle2.setForeground(java.awt.Color.white);
        vehicle2.setText("Xe khách (xe đò)");
        vehicle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicle2ActionPerformed(evt);
            }
        });
        jPanel3.add(vehicle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

        numberOfVehicle.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        numberOfVehicle.setText("18H 123...");
        numberOfVehicle.setToolTipText("Số phương tiện");
        numberOfVehicle.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                numberOfVehicleFocusGained(evt);
            }
        });
        numberOfVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOfVehicleActionPerformed(evt);
            }
        });
        jPanel3.add(numberOfVehicle, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 250, 40));

        jLabel16.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 24)); // NOI18N
        jLabel16.setForeground(java.awt.Color.white);
        jLabel16.setText("Ngày khởi hành");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, -1, -1));

        jLabel17.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 24)); // NOI18N
        jLabel17.setForeground(java.awt.Color.white);
        jLabel17.setText("Tỉnh/ Thành phố");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, -1, -1));
        jPanel3.add(datePicker, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 550, 280, 40));

        jLabel18.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 36)); // NOI18N
        jLabel18.setForeground(java.awt.Color.white);
        jLabel18.setText("1. Phương tiện");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel19.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 24)); // NOI18N
        jLabel19.setForeground(java.awt.Color.white);
        jLabel19.setText("Số hiệu phương tiện");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, -1, -1));

        citysCome.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                citysComeItemStateChanged(evt);
            }
        });
        citysCome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                citysComeActionPerformed(evt);
            }
        });
        jPanel3.add(citysCome, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 350, 40));

        jLabel21.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 24)); // NOI18N
        jLabel21.setForeground(java.awt.Color.white);
        jLabel21.setText("Địa chỉ cụ thể ( số nhà/ Tổ dân phố...)");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 490, -1, -1));
        jPanel3.add(districtsCome, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 410, 350, 40));

        jLabel22.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 24)); // NOI18N
        jLabel22.setForeground(java.awt.Color.white);
        jLabel22.setText("Quận/ Huyện");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, -1, -1));

        addressCome.setFont(new java.awt.Font("Noto Serif CJK TC", 0, 18)); // NOI18N
        jPanel3.add(addressCome, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 550, 450, 40));

        jLabel23.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 36)); // NOI18N
        jLabel23.setForeground(java.awt.Color.white);
        jLabel23.setText("3. Nơi người khai đi");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 120, -1, -1));

        jLabel24.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 24)); // NOI18N
        jLabel24.setForeground(java.awt.Color.white);
        jLabel24.setText("Tỉnh/ Thành phố");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 220, -1, -1));

        citysTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                citysToActionPerformed(evt);
            }
        });
        jPanel3.add(citysTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 270, 350, 40));

        jLabel25.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 24)); // NOI18N
        jLabel25.setForeground(java.awt.Color.white);
        jLabel25.setText("Quận/ Huyện");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 360, -1, -1));
        jPanel3.add(districtsTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 410, 350, 40));

        jLabel26.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 24)); // NOI18N
        jLabel26.setForeground(java.awt.Color.white);
        jLabel26.setText("Địa chỉ cụ thể ( số nhà/ Tổ dân phố...)");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 490, -1, -1));

        addressTo.setFont(new java.awt.Font("Noto Serif CJK TC", 0, 18)); // NOI18N
        jPanel3.add(addressTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 550, 450, 40));

        cancel.setBackground(java.awt.Color.white);
        cancel.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 24)); // NOI18N
        cancel.setForeground(new java.awt.Color(116, 214, 193));
        cancel.setText("Hủy tờ khai");
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
        });
        jPanel3.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 640, 230, 60));

        submit.setBackground(java.awt.Color.white);
        submit.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 24)); // NOI18N
        submit.setForeground(new java.awt.Color(116, 214, 193));
        submit.setText("Gửi tờ khai");
        submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitMouseClicked(evt);
            }
        });
        jPanel3.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 640, 230, 60));

        jPanel4.setBackground(new java.awt.Color(220, 153, 141));

        jLabel1.setIcon(new javax.swing.ImageIcon("/home/nhatnguyen/anh/icons8-user-128.png")); // NOI18N

        firstName.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 24)); // NOI18N
        firstName.setForeground(java.awt.Color.white);

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("ID:");

        idUser.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        idUser.setForeground(java.awt.Color.white);

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("Name:");

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("State:");

        state.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 24)); // NOI18N
        state.setForeground(java.awt.Color.white);

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("CardID:");

        cardId.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 24)); // NOI18N
        cardId.setForeground(java.awt.Color.white);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel5)
                                .addGap(8, 8, 8)
                                .addComponent(idUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(7, 7, 7)
                                .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(state, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cardId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(idUser, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(cardId, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(state, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(116, 214, 193));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon("/home/nhatnguyen/anh/icons8-warning-96.png")); // NOI18N
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 15)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("HÃY ĐẢM BẢO THÔNG TIN CHÍNH XÁC");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 320, 40));

        jLabel4.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 15)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Những điều bạn khai báo sẽ ");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 220, 40));

        jLabel9.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 15)); // NOI18N
        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setText("được sử dụng để khoanh vùng bệnh");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 280, 40));

        jLabel10.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 15)); // NOI18N
        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setText("Toàn bộ thông tin sẽ được bảo mật");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 270, 40));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vehicle3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicle3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vehicle3ActionPerformed

    private void vehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vehicleActionPerformed

    private void vehicle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicle2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vehicle2ActionPerformed

    private void numberOfVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberOfVehicleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberOfVehicleActionPerformed

    private void numberOfVehicleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numberOfVehicleFocusGained
        // TODO add your handling code here:
        numberOfVehicle.setText("");
    }//GEN-LAST:event_numberOfVehicleFocusGained

    private void citysComeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_citysComeItemStateChanged
        // TODO add your handling code here: 
    }//GEN-LAST:event_citysComeItemStateChanged

    private void citysComeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_citysComeActionPerformed
        // TODO add your handling code here:
        districtsCome.removeAllItems();
        int citySelected = citysCome.getSelectedIndex();
        for(int i = 0; i < listCity.get(citySelected).getDistricts().size(); i++){
           districtsCome.addItem(listCity.get(citySelected).getDistricts().get(i).getNameDistrict());
        }
    }//GEN-LAST:event_citysComeActionPerformed

    private void citysToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_citysToActionPerformed
        // TODO add your handling code here:
        districtsTo.removeAllItems();
        int citySelected = citysTo.getSelectedIndex();
        for(int i = 0; i < listCity.get(citySelected).getDistricts().size(); i++){
           districtsTo.addItem(listCity.get(citySelected).getDistricts().get(i).getNameDistrict());
        }
    }//GEN-LAST:event_citysToActionPerformed

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(jPanel3,
                        "Bạn muốn hủy bản khai báo trên?",
                        "Xác nhận",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE);
        if(result == JOptionPane.YES_OPTION){
            dispose();
        }
    }//GEN-LAST:event_cancelMouseClicked

    private void submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseClicked
        // TODO add your handling code here:
        String numberOfVehicle = this.numberOfVehicle.getText();
        String cityCome = VNCharacterUtils.removeAccent(this.citysCome.getSelectedItem().toString());
        String cityTo = VNCharacterUtils.removeAccent(this.citysTo.getSelectedItem().toString());
        String districtCome = VNCharacterUtils.removeAccent(this.districtsCome.getSelectedItem().toString());
        String districtTo = VNCharacterUtils.removeAccent(this.districtsTo.getSelectedItem().toString());
        String addressCome = this.addressCome.getText();
        String addressTo = this.addressTo.getText();
        String vehicle;
        LocalDate localDate = this.datePicker.getDate();
        if("".equals(numberOfVehicle)){
           JOptionPane.showMessageDialog(jPanel3,
                "Số hiệu phương tiện không được để trống",
                "Error numberOfVehicle",
                JOptionPane.ERROR_MESSAGE);
        }else if("".equals(addressCome)){
            JOptionPane.showMessageDialog(jPanel3,
                "Nơi đi không được để trống",
                "Error address",
                JOptionPane.ERROR_MESSAGE);
        }else if("".equals(addressTo)){
            JOptionPane.showMessageDialog(jPanel3,
                "Nơi đến không được để trống",
                "Error address",
                JOptionPane.ERROR_MESSAGE);
        }else if("".equals(localDate)){
            JOptionPane.showMessageDialog(jPanel3,
                "Thời gian đi không được để trống",
                "Error Time",
                JOptionPane.ERROR_MESSAGE);
        }else{
            if(this.vehicle.isSelected()){
                vehicle = "phuong tien ca nhan";
            }else if(this.vehicle2.isSelected()){
                vehicle = "xe khach";
            }else{
                vehicle = "tau thuyen";
            }
            String addStr = formDeclareInfor(numberOfVehicle,addressCome,addressTo,String.valueOf(localDate),cityCome,cityTo,districtCome,districtTo,vehicle);
            try {
                int result = JOptionPane.showConfirmDialog(jPanel3,
                                "Bạn muốn gửi bản khai báo trên?",
                                "Xác nhận",
                                JOptionPane.YES_NO_OPTION,
                                JOptionPane.QUESTION_MESSAGE);
                if(result == JOptionPane.YES_OPTION){
                    sendMessageToServer("8",socket);
                    sendMessageToServer(addStr,socket);
                    String receivedMessage;
                    InputStream istream = socket.getInputStream();
                    BufferedReader receiveRead = new BufferedReader(new InputStreamReader(istream), 1024);
                    receivedMessage = getMessageFromServer(receiveRead,socket);
                    if(!receivedMessage.equals("")){
                        JOptionPane.showMessageDialog(jPanel3,
                        receivedMessage,
                        "From Server",
                        JOptionPane.INFORMATION_MESSAGE);
                        dispose();
                    }
                }
               
            } catch (Exception e) {
            }
            
            System.out.println("numberOfVehircle: " + numberOfVehicle);
            System.out.println("addressCome: " + addressCome);
            System.out.println("addressTo: " + addressTo);
            System.out.println("localDate: " + localDate);
            System.out.println("cityCome: " + cityCome);
            System.out.println("cityTo: " + cityTo);
            System.out.println("districtCome: " + districtCome);
            System.out.println("districtTo: " + districtTo);
            System.out.println("vehicle: " + vehicle);
        }
    }//GEN-LAST:event_submitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LocalPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LocalPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LocalPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LocalPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new LocalPage().setVisible(true);
                } catch (Exception e) {
                }

            }
        });
    }

    private String getMessageFromServer(BufferedReader receiveRead, Socket socket) throws IOException {
        String receiveMessage;
        receiveMessage = String.valueOf(receiveRead.readLine());
        receiveMessage = removeNonAscii(receiveMessage);
        receiveMessage = replaceUnreadable(receiveMessage);
        if(!Objects.equals(receiveMessage, "0")) //receive from server
        {
            System.out.print("from server: ");
            System.out.println(receiveMessage); // displaying at DOS prompt
        }
        return receiveMessage;
    }

    private static String removeNonAscii(String s){
        StringBuffer sb = new StringBuffer();
        for(int i=0; i<s.length(); ++i){
            if(s.charAt(i) < 128){
                sb.append(s.charAt(i));
            }
        }
        return sb.toString();
    }

    private static String replaceUnreadable(String s){
        return s.replaceAll("\\P{Print}", "");
    }

    private void sendMessageToServer(String str, Socket sock) throws IOException {
        OutputStream ostream = sock.getOutputStream();
        PrintWriter pwrite = new PrintWriter(ostream, true);
        pwrite.println(str);       // sending to server
        pwrite.flush();            // flush the data
    }

    private String formDeclareInfor(String numberOfVehircle,String addressCome,String addressTo,String localDate,String cityCome,String cityTo,String districtCome,String districtTo,String vehicle){
        return numberOfVehircle+"_"+addressCome+"_"+addressTo+"_"+localDate+"_"+cityCome+"_"+cityTo+"_"+districtCome+"_"+districtTo+"_"+vehicle;
    }

    public static void startLayout(Socket socket, account user){
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new LocalPage(socket,user).setVisible(true);
                } catch (Exception e) {
                }

            }
        });
    }

    private void addCity(){
        for(int i = 0; i < listCity.size(); i++){
            citysCome.addItem(listCity.get(i).getName());
            citysTo.addItem(listCity.get(i).getName());
        }
    }

    private void addInforUser(){
        this.idUser.setText(user.getIdUser());
        this.firstName.setText(user.getFirstName());
        this.cardId.setText(user.getCardId());
        this.state.setText(user.getState());
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressCome;
    private javax.swing.JTextField addressTo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancel;
    private javax.swing.JLabel cardId;
    private javax.swing.JComboBox<String> citysCome;
    private javax.swing.JComboBox<String> citysTo;
    private com.github.lgooddatepicker.components.DatePicker datePicker;
    private javax.swing.JComboBox<String> districtsCome;
    private javax.swing.JComboBox<String> districtsTo;
    private javax.swing.JLabel firstName;
    private javax.swing.JLabel idUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField numberOfVehicle;
    private javax.swing.JLabel state;
    private javax.swing.JButton submit;
    private javax.swing.JRadioButton vehicle;
    private javax.swing.JRadioButton vehicle2;
    private javax.swing.JRadioButton vehicle3;
    // End of variables declaration//GEN-END:variables
}
