/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1.loginForm;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.io.PrintWriter;
import java.net.Socket;
import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author nhatnguyen
 */
public class SignUpInfor extends javax.swing.JFrame {
    Socket socket;
    private String idUser;

    /**
     * Creates new form Home
     */
    public SignUpInfor(Socket socketSignUp) throws IOException{
        socket = socketSignUp;
        initComponents();
        Dimension objDimension = Toolkit.getDefaultToolkit().getScreenSize();
        int iCoordX = (objDimension.width - this.getWidth()) / 2;
        int iCoordY = (objDimension.height - this.getHeight()) / 2;
        this.setLocation(iCoordX, iCoordY);
    }

    public SignUpInfor(){

    }

   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        firstName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lastName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cardID = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        birthOfDay = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        numberPhone = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        sendInfor = new javax.swing.JButton();
        nuRadioBtn = new javax.swing.JRadioButton();
        namRadioBtn = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(116, 214, 193));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("PC COVID");

        jLabel2.setBackground(java.awt.Color.white);
        jLabel2.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("KHAI BÁO Y TẾ - GIẢM THIỂU LÂY LAN");

        jLabel3.setIcon(new javax.swing.ImageIcon("/home/nhatnguyen/Downloads/icons8-protect-128.png")); // NOI18N

        jLabel4.setFont(new java.awt.Font("Noto Serif CJK JP", 1, 36)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Thông tin cơ bản");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 25)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("First name:");

        firstName.setFont(new java.awt.Font("Noto Serif CJK TC", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 25)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("Last name:");

        lastName.setFont(new java.awt.Font("Noto Serif CJK TC", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 25)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("Your ID:");

        cardID.setFont(new java.awt.Font("Noto Serif CJK TC", 0, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 25)); // NOI18N
        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("Birth Day:");

        birthOfDay.setFont(new java.awt.Font("Noto Serif CJK TC", 0, 18)); // NOI18N
        birthOfDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birthOfDayActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 25)); // NOI18N
        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setText("Gender:");

        jLabel10.setFont(new java.awt.Font("Ubuntu", 1, 25)); // NOI18N
        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setText("Phone number:");

        numberPhone.setFont(new java.awt.Font("Noto Serif CJK TC", 0, 18)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Ubuntu", 1, 25)); // NOI18N
        jLabel11.setForeground(java.awt.Color.white);
        jLabel11.setText("Email:");

        email.setFont(new java.awt.Font("Noto Serif CJK TC", 0, 18)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Ubuntu", 1, 25)); // NOI18N
        jLabel12.setForeground(java.awt.Color.white);
        jLabel12.setText("Address:");

        address.setFont(new java.awt.Font("Noto Serif CJK TC", 0, 18)); // NOI18N

        sendInfor.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        sendInfor.setForeground(new java.awt.Color(116, 214, 193));
        sendInfor.setText("Send your information");
        sendInfor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                try {
                    sendInforMouseClicked(evt);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        });

        buttonGroup1.add(nuRadioBtn);
        nuRadioBtn.setFont(new java.awt.Font("Noto Serif CJK SC", 1, 30)); // NOI18N
        nuRadioBtn.setForeground(java.awt.Color.white);
        nuRadioBtn.setText("Nữ");
        nuRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuRadioBtnActionPerformed(evt);
            }
        });

        buttonGroup1.add(namRadioBtn);
        namRadioBtn.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 30)); // NOI18N
        namRadioBtn.setForeground(java.awt.Color.white);
        namRadioBtn.setSelected(true);
        namRadioBtn.setText("Nam");
        namRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namRadioBtnActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel13.setForeground(java.awt.Color.white);
        jLabel13.setText("(dd-mm-yyy)");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(sendInfor, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(449, 449, 449))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(487, 487, 487)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel6)
                                                .addComponent(jLabel7))
                                            .addGap(18, 18, 18)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(cardID, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel8)
                                                .addComponent(jLabel13))
                                            .addGap(18, 18, 18)
                                            .addComponent(birthOfDay, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel11)
                                            .addGap(18, 18, 18)
                                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel10)
                                            .addGap(18, 18, 18)
                                            .addComponent(numberPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(18, 18, 18)
                                        .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(171, 171, 171)
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(namRadioBtn)
                                .addGap(29, 29, 29)
                                .addComponent(nuRadioBtn)))))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(44, 44, 44)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5)))
                                    .addComponent(numberPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel11))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cardID, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(birthOfDay, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(namRadioBtn)
                        .addComponent(nuRadioBtn))
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(sendInfor, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void birthOfDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthOfDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_birthOfDayActionPerformed

    private void nuRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuRadioBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuRadioBtnActionPerformed

    private void namRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namRadioBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namRadioBtnActionPerformed

    private void sendInforMouseClicked(java.awt.event.MouseEvent evt) throws IOException {//GEN-FIRST:event_sendInforMouseClicked
        // TODO add your handling code here:
        String firstName = this.firstName.getText();
        String lastName = this.lastName.getText();
        String carId = this.cardID.getText();
        String birthDay = this.birthOfDay.getText();
        String gender;
        if(this.namRadioBtn.isSelected()){
           gender = "Nam";
        }else{
           gender = "Nu";
        }
        String numberPhone = this.numberPhone.getText();
        String email = this.email.getText();
        String address = this.address.getText();
        if("".equals(firstName) || "".equals(lastName) || "".equals(carId) || "".equals(birthDay) || "".equals(numberPhone) || "".equals(email) || "".equals(address)){
           JOptionPane.showMessageDialog(jLabel3,
                "Không được để trống thông tin cá nhân",
                "Error form",
                JOptionPane.ERROR_MESSAGE);
        }
//        userAccount.setIdUser(idUser);
//        userAccount.setFirstName(firstName);
//        userAccount.setLastname(lastName);
//        userAccount.setCardId(carId);
//        userAccount.setBirthOfDay(birthDay);
//        userAccount.setGender(gender);
//        userAccount.setNumberPhone(numberPhone);
//        userAccount.setEmail(email);
//        userAccount.setAddress(address);
//        userAccount.setState("normal");
//        System.out.println("idUser : " + this.idUser);
        String message = createInforAccountMessage(" ",firstName,lastName,carId,birthDay,gender,numberPhone,email,address,"normal");
        System.out.println("string gui: " + message);
        sendMessageToServer(message,socket);
        InputStream istream = socket.getInputStream();
        BufferedReader receiveRead = new BufferedReader(new InputStreamReader(istream), 1024);
        String receiveMessage2;
        receiveMessage2 = String.valueOf(receiveRead.readLine());
        receiveMessage2 = removeNonAscii(receiveMessage2);
        receiveMessage2 = replaceUnreadable(receiveMessage2);
        if(!Objects.equals(receiveMessage2, "0")) //receive from server
        {
            System.out.print("from server: ");
            System.out.println(receiveMessage2); // displaying at DOS prompt
            if(receiveMessage2.equals("Create information successfully -> Let login to PC COVID")){
                JOptionPane.showMessageDialog(jPanel2,
                    "Create information successfully -> Let login to PC COVID",
                    "From Server",
                    JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(jPanel2,
                    "Create information Error -> Please create a new account",
                    "From Server",
                    JOptionPane.INFORMATION_MESSAGE);
            }
            socket.close();
            dispose();
            NewSignUp login = null;
            login = new NewSignUp("");
            login.startLayout();
        }
    }//GEN-LAST:event_sendInforMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(sign_up_infor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(sign_up_infor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(sign_up_infor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(sign_up_infor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new sign_up_infor().setVisible(true);
//            }
//        });
//    }

    public void startLayout(Socket socket){
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new SignUpInfor(socket).setVisible(true);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        });
    }

    private String createInforAccountMessage(String idUser, String firstName, String lastName, String cardId, String birthday, String gender, String numberPhone,String email, String address, String state){
        return idUser + "_" + firstName + "_" + lastName + "_" + cardId + "_" + birthday + "_" + gender + "_" + numberPhone + "_" +email + "_" + address + "_" + state;
    }

    private void sendMessageToServer(String str, Socket sock) throws IOException {
        OutputStream ostream = sock.getOutputStream();
        PrintWriter pwrite = new PrintWriter(ostream, true);
        pwrite.println(str);       // sending to server
        pwrite.flush();            // flush the data
    }

    private static String removeNonAscii(String s){
        StringBuffer sb = new StringBuffer();
        for(int i=0; i<s.length(); ++i){
            if(s.charAt(i) < 128){
                sb.append(s.charAt(i));
            }
        }
        return sb.toString();
    }

    private static String replaceUnreadable(String s){
        return s.replaceAll("\\P{Print}", "");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JTextField birthOfDay;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cardID;
    private javax.swing.JTextField email;
    private javax.swing.JTextField firstName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField lastName;
    private javax.swing.JRadioButton namRadioBtn;
    private javax.swing.JRadioButton nuRadioBtn;
    private javax.swing.JTextField numberPhone;
    private javax.swing.JButton sendInfor;
    // End of variables declaration//GEN-END:variables
}
